var name = "banita";
let age = 23;
const city = "Bhubaneswar";
console.log(age);
console.log(name);
console.log(city);
console.log(add);
var add = "jajpur";
console.log(add);
let user = null;
console.log(user);
console.log(typeof null);
let num = 23;
let decimal_no = 2.3;
let pi = 3.14;
let roll_no = 22;
console.log(typeof num);
let num1 = 23;
let num2 = 45;
let addition = num1 + num2;
console.log(addition);

let num3 = 45;
let num4 = 34;
let substraction = num3 - num4;
let multiple = num3 * num4;
let division = num3 / num4;
console.log(substraction);
console.log(multiple);
console.log(division);
